# Generated by Django 5.1 on 2024-08-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='codigo_barras',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
