# Generated by Django 5.1 on 2024-08-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_products_codigo_barras_products_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='codigo_barras',
            field=models.CharField(max_length=999999, unique=True),
        ),
    ]
